const PREFIX = 'BOOKING/'

const bookingAction = {
    //get all
    GET_PAGGING_BOOKINGS: PREFIX + 'GET_PAGGING_BOOKINGS',
    GET_PAGGING_BOOKINGS_SUCCESS: PREFIX + 'GET_PAGGING_BOOKINGS_SUCCESS',
    GET_PAGGING_BOOKINGS_FAIL: PREFIX + 'GET_PAGGING_BOOKINGS_FAIL',

    //change action
    CHANGE_ACTION: PREFIX + 'CHANGE_ACTION',

    //page change
    PAGE_CHANGE: PREFIX + 'PAGE_CHANGE',

    //select
    SELECT_BOOKING: PREFIX + 'SELECT_BOOKING',

    //show detail branch 
    SHOW_DETAIL_BOOKING_MODAL: PREFIX + 'SHOW_DETAIL_BOOKING_MODAL',
    HIDE_DETAIL_BOOKING_MODAL: PREFIX + 'HIDE_DETAIL_BOOKING_MODAL',
}


export default bookingAction;