const PREFIX = 'BRANCH/'

const branchAction = {
    //get all
    GET_PAGGING_BRANCHES: PREFIX + 'GET_PAGGING_BRANCHES',
    GET_PAGGING_BRANCHES_SUCCESS: PREFIX + 'GET_PAGGING_BRANCHES_SUCCESS',
    GET_PAGGING_BRANCHES_FAIL: PREFIX + 'GET_PAGGING_BRANCHES_FAIL',

    //change action
    CHANGE_ACTION: PREFIX + 'CHANGE_ACTION',
    
    //add
    ADD_BRANCH: PREFIX + 'ADD_BRANCH',
    ADD_BRANCH_SUCCESS: PREFIX + 'ADD_BRANCH_SUCCESS',
    ADD_BRANCH_FAIL: PREFIX + 'ADD_BRANCH_FAIL',

    //add detail
    ADD_BRANCH_DETAIL: PREFIX + 'ADD_BRANCH_DETAIL',
    ADD_BRANCH_DETAIL_SUCCESS: PREFIX + 'ADD_BRANCH_DETAIL_SUCCESS',
    ADD_BRANCH_DETAIL_FAIL: PREFIX + 'ADD_BRANCH_DETAIL_FAIL',

    //delete
    DELETE_BRANCH: PREFIX + 'DELETE_BRANCH',
    DELETE_BRANCH_SUCCESS: PREFIX + 'DELETE_BRANCH_SUCCESS',
    DELETE_BRANCH_FAIL: PREFIX + 'DELETE_BRANCH_FAIL',

    SELECT_BRANCH: PREFIX + 'SELECT_BRANCH',
    //show add branch 
    SHOW_ADD_BRANCH_MODAL: PREFIX + 'SHOW_ADD_BRANCH_MODAL',
    HIDE_ADD_BRANCH_MODAL: PREFIX + 'HIDE_ADD_BRANCH_MODAL',

    //show delet service 
    SHOW_DELETE_BRANCH_MODAL: PREFIX + 'SHOW_DELETE_BRANCH_MODAL',
    HIDE_DELETE_BRANCH_MODAL: PREFIX + 'HIDE_DELETE_BRANCH_MODAL',
}


export default branchAction;