const PREFIX = 'CHECK_IN/'

const checkinAction = {
    //get all
    GET_PAGGING_CHECK_IN_CUSTOMERS: PREFIX + 'GET_PAGGING_CHECK_IN_CUSTOMERS',
    GET_PAGGING_CHECK_IN_CUSTOMERS_SUCCESS: PREFIX + 'GET_PAGGING_CHECK_IN_CUSTOMERS_SUCCESS',
    GET_PAGGING_CHECK_IN_CUSTOMERS_FAIL: PREFIX + 'GET_PAGGING_CHECK_IN_CUSTOMERS_FAIL',

    //change action
    CHANGE_ACTION: PREFIX + 'CHANGE_ACTION',
    CHANGE_LOADING: PREFIX + 'CHANGE_LOADING',

    //page change
    PAGE_CHANGE: PREFIX + 'PAGE_CHANGE',
    
    SELECT_CHECK_IN_CUSTOMER: PREFIX + 'SELECT_CHECK_IN_CUSTOMER',
    
    //get combo branches
    GET_COMBO_BRANCHES: PREFIX + 'GET_COMBO_BRANCHES',
    GET_COMBO_BRANCHES_SUCCESS: PREFIX + 'GET_COMBO_BRANCHES_SUCCESS',
    GET_COMBO_BRANCHES_FAIL: PREFIX + 'GET_COMBO_BRANCHES_FAIL',

    //get combo levels
    GET_COMBO_LEVELS: PREFIX + 'GET_COMBO_LEVELS',
    GET_COMBO_LEVELS_SUCCESS: PREFIX + 'GET_COMBO_LEVELS_SUCCESS',
    GET_COMBO_LEVELS_FAIL: PREFIX + 'GET_COMBO_LEVELS_FAIL',

    //show detail check in 
    SHOW_DETAIL_CHECK_IN_MODAL: PREFIX + 'SHOW_DETAIL_CHECK_IN_MODAL',
    HIDE_DETAIL_CHECK_IN_MODAL: PREFIX + 'HIDE_DETAIL_CHECK_IN_MODAL',
}


export default checkinAction;