const PREFIX = 'SERVICE/'

const serviceAction = {
    //get all
    GET_ALL_SERVICES: PREFIX + 'GET_ALL_SERVICES',
    GET_ALL_SERVICES_SUCCESS: PREFIX + 'GET_ALL_SERVICES_SUCCESS',
    GET_ALL_SERVICES_FAIL: PREFIX + 'GET_ALL_SERVICES_FAIL',

    //change action
    CHANGE_ACTION: PREFIX + 'CHANGE_ACTION',
    
    //add
    ADD_SERVICE: PREFIX + 'ADD_SERVICE',
    ADD_SERVICE_SUCCESS: PREFIX + 'ADD_SERVICE_SUCCESS',
    ADD_SERVICE_FAIL: PREFIX + 'ADD_SERVICE_FAIL',

    //add detail
    ADD_SERVICE_DETAIL: PREFIX + 'ADD_SERVICE_DETAIL',
    ADD_SERVICE_DETAIL_SUCCESS: PREFIX + 'ADD_SERVICE_DETAIL_SUCCESS',
    ADD_SERVICE_DETAIL_FAIL: PREFIX + 'ADD_SERVICE_DETAIL_FAIL',

    //delete
    DELETE_SERVICE: PREFIX + 'DELETE_SERVICE',
    DELETE_SERVICE_SUCCESS: PREFIX + 'DELETE_SERVICE_SUCCESS',
    DELETE_SERVICE_FAIL: PREFIX + 'DELETE_SERVICE_FAIL',

    SELECT_SERVICE: PREFIX + 'SELECT_SERVICE',
    //show service detail modal
    SHOW_SERVICE_DETAILS_MODAL: PREFIX + 'SHOW_SERVICE_DETAILS_MODAL',
    HIDE_SERVICE_DETAILS_MODAL: PREFIX + 'HIDE_SERVICE_DETAILS_MODAL',
}

export default serviceAction;